version: "3"

services:
  nginx-web:
    image: nginx:1.18.0-alpine
    container_name: nginx-web
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/htpasswd:/etc/nginx/htpasswd:ro
      - ./data/vhost.d:/etc/nginx/vhost.d:ro
      - ./data/html:/usr/share/nginx/html:ro
    networks:
      - default
      - outside
  nginx-gen:
    image: jwilder/docker-gen:0.7.3
    command: -notify-sighup nginx-web -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    container_name: nginx-gen
    restart: always
    volumes:
      - ./data/certs:/etc/nginx/certs:ro
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/htpasswd:/etc/nginx/htpasswd:ro
      - ./data/vhost.d:/etc/nginx/vhost.d:ro
      - ./data/html:/usr/share/nginx/html:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./data/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    networks:
      - default
      - outside
  nginx-ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.13.1
    container_name: nginx-ssl
    restart: always
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_PROXY_CONTAINER: nginx-web
      NGINX_DOCKER_GEN_CONTAINER: nginx-gen
    networks:
      - default
      - outside

networks:
  default:
    external:
      name: webgen
  outside:
    external:
      name: services
